export const businessInfo = {
  name: "Sancheti Computers",
  owner: "Mahendra Kumar",
  established: 2012,
  tagline: "Trusted IT Solutions Since 2012",
  description: "Your trusted partner for IT hardware, software, networking products, and technical support solutions in Bengaluru.",
  address: {
    street: "112, Sadar Patrappa Road",
    area: "Dodpete, Nagarathpete",
    city: "Bengaluru",
    state: "Karnataka",
    pincode: "560002",
    full: "112, Sadar Patrappa Road, Dodpete, Nagarathpete, Bengaluru, Karnataka - 560002",
  },
  phone: "+918050773494",
  phoneFormatted: "+91 80507 73494",
  email: "sales@sancheticomputers.com",
  whatsapp: "918050773494",
  hours: {
    days: "Monday - Saturday",
    time: "10:00 AM - 8:00 PM",
  },
  social: {
    facebook: "#",
    instagram: "#",
    twitter: "#",
    linkedin: "#",
  },
  googleMapsUrl: "https://www.google.com/maps/place/Sancheti+Computers/@12.9716,77.5726,17z",
  googleReviewUrl: "https://g.page/sancheticomputers/review",
};

export const services = [
  { title: "Computer Sales", description: "Desktops and towers from top brands for home and business use.", icon: "Monitor" },
  { title: "Laptop Sales", description: "Laptops for students, professionals, and enterprises at best prices.", icon: "Laptop" },
  { title: "Desktop Assembly", description: "Custom-built desktops assembled to your exact specifications.", icon: "Cpu" },
  { title: "Networking Solutions", description: "Routers, switches, cabling, and complete network setup.", icon: "Network" },
  { title: "WiFi Devices", description: "Access points, extenders, and mesh WiFi systems.", icon: "Wifi" },
  { title: "Printers & Peripherals", description: "Printers, scanners, and peripherals from leading brands.", icon: "Printer" },
  { title: "Software Solutions", description: "Licensed OS, antivirus, and productivity software.", icon: "Disc" },
  { title: "Computer Accessories", description: "Keyboards, mice, headsets, webcams, and more.", icon: "Keyboard" },
  { title: "CCTV & Surveillance", description: "CCTV cameras, DVRs, NVRs, and security system installation.", icon: "Camera" },
  { title: "IT Infrastructure Setup", description: "Complete IT setup for offices, schools, and enterprises.", icon: "Building" },
  { title: "System Upgrades", description: "RAM, SSD, processor upgrades to boost performance.", icon: "ArrowUpCircle" },
  { title: "Computer Repairs", description: "Expert diagnosis and repair for all computer issues.", icon: "Wrench" },
  { title: "Enterprise IT Procurement", description: "Bulk IT hardware procurement solutions for businesses.", icon: "Briefcase" },
];

export const products = [
  {
    id: 1,
    name: "HP Pavilion Laptop",
    category: "Laptops",
    price: "Starting ₹45,000",
    image: "/products/laptop.jpg",
    description: "Powerful performance for everyday computing with HP Pavilion series.",
    specs: ["Intel Core i5/i7", "8GB/16GB RAM", "512GB SSD", "15.6\" FHD Display"],
    badge: "Best Seller",
  },
  {
    id: 2,
    name: "Dell Inspiron Desktop",
    category: "Desktops",
    price: "Starting ₹35,000",
    image: "/products/desktop.jpg",
    description: "Reliable desktop solutions for home and office use.",
    specs: ["Intel Core i3/i5", "8GB RAM", "1TB HDD + 256GB SSD", "Windows 11"],
    badge: "Popular",
  },
  {
    id: 3,
    name: "Custom Gaming PC",
    category: "Gaming Systems",
    price: "Starting ₹85,000",
    image: "/products/gaming.jpg",
    description: "High-performance custom gaming builds with premium components.",
    specs: ["Intel Core i7/i9 or AMD Ryzen", "16GB/32GB RAM", "RTX 4060/4070", "1TB NVMe SSD"],
    badge: "Premium",
  },
  {
    id: 4,
    name: "HP LaserJet Printer",
    category: "Printers",
    price: "Starting ₹12,000",
    image: "/products/printer.jpg",
    description: "Fast and efficient laser printing for offices and businesses.",
    specs: ["Print Speed: 28ppm", "Auto Duplex", "WiFi & USB", "HP Smart App"],
    badge: null,
  },
  {
    id: 5,
    name: "TP-Link Router",
    category: "Networking Equipment",
    price: "Starting ₹2,500",
    image: "/products/router.jpg",
    description: "High-speed wireless routers for seamless connectivity.",
    specs: ["Dual Band WiFi 6", "Up to 1500 Mbps", "4 x LAN Ports", "Easy Setup"],
    badge: null,
  },
  {
    id: 6,
    name: "Samsung 1TB SSD",
    category: "SSDs & Storage",
    price: "Starting ₹6,500",
    image: "/products/ssd.jpg",
    description: "Lightning-fast storage upgrade for your computer.",
    specs: ["1TB Capacity", "560 MB/s Read", "530 MB/s Write", "SATA III"],
    badge: "Fast",
  },
  {
    id: 7,
    name: "Corsair 16GB RAM",
    category: "RAM & Components",
    price: "Starting ₹4,500",
    image: "/products/ram.jpg",
    description: "Premium memory modules for enhanced multitasking.",
    specs: ["16GB DDR4", "3200MHz Speed", "Low Profile", "Heat Spreader"],
    badge: null,
  },
  {
    id: 8,
    name: "LG 24\" Monitor",
    category: "Monitors",
    price: "Starting ₹12,000",
    image: "/products/monitor.jpg",
    description: "Crystal-clear display for work and entertainment.",
    specs: ["24-inch IPS Panel", "Full HD 1080p", "75Hz Refresh Rate", "HDMI + VGA"],
    badge: null,
  },
  {
    id: 9,
    name: "Hikvision CCTV Kit",
    category: "CCTV Products",
    price: "Starting ₹8,000",
    image: "/products/cctv.jpg",
    description: "Complete security solution with professional installation.",
    specs: ["4 Camera Kit", "2MP Full HD", "Night Vision", "Mobile Viewing"],
    badge: "Installed",
  },
  {
    id: 10,
    name: "Logitech Keyboard & Mouse",
    category: "Computer Accessories",
    price: "Starting ₹1,200",
    image: "/products/accessories.jpg",
    description: "Ergonomic peripherals for comfortable daily use.",
    specs: ["Wireless Combo", "Full Size Keyboard", "1000 DPI Mouse", "Plug & Play"],
    badge: null,
  },
  {
    id: 11,
    name: "Lenovo ThinkPad",
    category: "Laptops",
    price: "Starting ₹55,000",
    image: "/products/laptop2.jpg",
    description: "Business-class laptop built for reliability and performance.",
    specs: ["Intel Core i5/i7", "8GB/16GB RAM", "512GB SSD", "14\" FHD Anti-glare"],
    badge: "Business",
  },
  {
    id: 12,
    name: "Dell 27\" Monitor",
    category: "Monitors",
    price: "Starting ₹18,000",
    image: "/products/monitor2.jpg",
    description: "Large-screen monitor for productivity and multitasking.",
    specs: ["27-inch IPS", "QHD 1440p", "75Hz Refresh", "USB-C Hub"],
    badge: null,
  },
];

export const productCategories = [
  "All",
  "Laptops",
  "Desktops",
  "Gaming Systems",
  "Printers",
  "Networking Equipment",
  "SSDs & Storage",
  "RAM & Components",
  "Monitors",
  "CCTV Products",
  "Computer Accessories",
];

export const testimonials = [
  {
    name: "Rajesh Kumar",
    rating: 5,
    text: "Great Prices & Quality Products. Sancheti Computers has been my go-to store for all IT needs.",
    source: "Google",
  },
  {
    name: "Priya Sharma",
    rating: 5,
    text: "Best price compared to other stores, genuine service. Very professional team.",
    source: "Google",
  },
  {
    name: "Anand Patel",
    rating: 5,
    text: "Very good service and proper guidance for laptop purchases. Highly recommended!",
    source: "Google",
  },
  {
    name: "Vikram Reddy",
    rating: 5,
    text: "Reliable and genuine supplier for computers and accessories. Been buying from them for years.",
    source: "Google",
  },
  {
    name: "Sneha Gupta",
    rating: 4,
    text: "Excellent service and economical rates. They helped set up our entire office IT infrastructure.",
    source: "Google",
  },
  {
    name: "Manjunath M",
    rating: 5,
    text: "One of the best computer shops on SP Road. Knowledgeable staff and competitive prices.",
    source: "Google",
  },
];

export const brands = [
  "HP", "Dell", "Lenovo", "Acer", "ASUS", "Samsung",
  "Intel", "AMD", "TP-Link", "D-Link", "Logitech",
  "Canon", "Epson", "Hikvision", "Corsair", "Kingston",
];

export const stats = [
  { number: "8+", label: "Years Experience" },
  { number: "1000+", label: "Happy Customers" },
  { number: "100%", label: "Genuine Products" },
  { number: "50+", label: "Brands Available" },
];

export const customerSegments = [
  {
    id: "b2c",
    title: "Individual Buyers",
    subtitle: "B2C",
    description: "Laptops, desktops, accessories and upgrades for personal use. Expert guidance to find the perfect device for your needs.",
    features: ["Wide range of brands", "Best market prices", "Expert guidance", "After-sales support"],
    cta: "Browse Products",
    ctaLink: "/products",
  },
  {
    id: "b2b",
    title: "Businesses & Enterprises",
    subtitle: "B2B",
    description: "Bulk IT procurement, office setup, networking infrastructure, and ongoing support for companies of all sizes.",
    features: ["Bulk pricing", "Custom configurations", "On-site setup", "Dedicated support"],
    cta: "Request a Quote",
    ctaLink: "/quote",
  },
  {
    id: "gem",
    title: "Government (GEM)",
    subtitle: "GEM Registered",
    description: "Registered on Government e-Marketplace (GEM). Supply IT hardware, laptops, desktops, and networking equipment to government departments.",
    features: ["GEM Portal Registered", "Compliance assured", "Pan-Karnataka supply", "Competitive tenders"],
    cta: "GEM Enquiry",
    ctaLink: "https://wa.me/918050773494?text=Hi%2C%20I%27m%20interested%20in%20GEM%20procurement%20for%20government%20department.",
  },
];

export const gemInfo = {
  title: "Government e-Marketplace (GEM) Partner",
  description: "Sancheti Computers is registered on the Government e-Marketplace (GEM) portal, enabling us to supply IT hardware, laptops, desktops, printers, networking equipment, and CCTV systems to government departments, PSUs, and autonomous bodies across Karnataka and India.",
  features: [
    "GEM Portal Registered Vendor",
    "IT Hardware & Networking Supply",
    "Laptops, Desktops, Printers for Govt Offices",
    "CCTV & Surveillance Systems",
    "Pan-India Delivery Capability",
    "Compliance with GEM Terms & Conditions",
  ],
  ctaText: "Enquire on GEM Portal",
};
